### ISSUE TITLE
Mutiusers and natting.

### ISSUE THREAD

**Issue by fulup-bzh** [agroszer/komodo-python-dbgp#2]
While the introduction of 'remote_connect_back' on PHP Xdebug module solved the problem of multi-user when web server has network access to IDE client, the issue remains fatal when server or client is protected behind a nat.

Changing line 333 of pydbgpproxy replacing addr=xxxx with  addr= ['127.0.0.1',long(idekey)] makes proxy forward debug information on server network loopback. Each user can then use a simple ssh tunel to transfert debug information from server to its desktop IDE debug port, as they do in single user mode. Its not perfect, but it works and does not require to change firewall rules.

As today the default it for pydbgpproxy to push debug information to the IP/port that registered a given IDEkey. This cannot work in a natted environment. It would be nice to have an option or a syntax pattern for the key that change this behaviour.

Proposal: 
 --tunel=localhost push any information for a given registered IDEkey to localhost:port
--as a key partern  "MyIdeKey:tunelport"
etc....

Ideally we would like Xdebug PHP module to handle such a "special" key pattern, as this would directly as it would eliminate the requirement for proxy.

**Comment by pndx** [comment]
same problem. NAT make the server find wrong ip. I can't find a way to set ip manually.
